#############################################################################
# Generated by PAGE version 4.10
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+596+257
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3185 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bind $top <Button-1> {
        lambd
    }
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 421 \
        -width 565 
    vTcl:DefineAlias "$top.fra38" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra38
    text $site_3_0.tex39 \
        -background white -font TkTextFont -foreground black -height 31 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 125 \
        -wrap word 
    .top37.fra38.tex39 configure -font TkTextFont
    .top37.fra38.tex39 insert end text
    vTcl:DefineAlias "$site_3_0.tex39" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -background {#d9d9d9} -foreground {#000000} -text Time 
    vTcl:DefineAlias "$site_3_0.lab41" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu48 \
        -command start_tracker -takefocus {} -text Start 
    vTcl:DefineAlias "$site_3_0.tBu48" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu51 \
        -takefocus {} -text Laufen 
    vTcl:DefineAlias "$site_3_0.tBu51" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu53 \
        -takefocus {} -text Ruhen 
    vTcl:DefineAlias "$site_3_0.tBu53" "TButton4" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu54 \
        -takefocus {} -text {Antenne P} 
    vTcl:DefineAlias "$site_3_0.tBu54" "TButton5" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu55 \
        -takefocus {} -text {Putzen P} 
    vTcl:DefineAlias "$site_3_0.tBu55" "TButton6" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu56 \
        -takefocus {} -text {Antenne A} 
    vTcl:DefineAlias "$site_3_0.tBu56" "TButton7" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu57 \
        -takefocus {} -text {Putzen A} 
    vTcl:DefineAlias "$site_3_0.tBu57" "TButton8" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu59 \
        -takefocus {} -text {Zucken A} 
    vTcl:DefineAlias "$site_3_0.tBu59" "TButton10" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu64 \
        -takefocus {} -text {Zucken P} 
    vTcl:DefineAlias "$site_3_0.tBu64" "TButton11" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu65 \
        -takefocus {} -text Anderes 
    vTcl:DefineAlias "$site_3_0.tBu65" "TButton12" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu66 \
        -takefocus {} -text {Troph. A} 
    vTcl:DefineAlias "$site_3_0.tBu66" "TButton13" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu67 \
        -takefocus {} -text {Troph. P} 
    vTcl:DefineAlias "$site_3_0.tBu67" "TButton14" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -background {#d9d9d9} -foreground {#000000} \
        -text {Big Termite, Copyright: Floßmann 2018} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu70 \
        -command start_tracker -takefocus {} -text Stop -state disabled 
    vTcl:DefineAlias "$site_3_0.tBu70" "TButton9" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che71 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -justify left \
        -state active -text Export -variable export_checker 
    vTcl:DefineAlias "$site_3_0.che71" "ExportChecker" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tex39 \
        -in $site_3_0 -x 210 -y 70 -width 125 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 240 -y 50 -width 66 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 420 -y 20 -width 97 -height 57 -anchor nw \
        -bordermode inside 
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 50 -y 210 -width 97 -height 57 -anchor nw \
        -bordermode inside 
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 54 -y 325 -width 97 -height 57 -anchor nw \
        -bordermode inside 
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 240 -y 220 -width 97 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu55 \
        -in $site_3_0 -x 240 -y 350 -width 97 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 240 -y 170 -width 97 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 240 -y 300 -width 97 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 420 -y 330 -width 97 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu64 \
        -in $site_3_0 -x 420 -y 370 -width 97 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu65 \
        -in $site_3_0 -x 420 -y 270 -width 97 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu66 \
        -in $site_3_0 -x 420 -y 170 -width 97 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.tBu67 \
        -in $site_3_0 -x 420 -y 210 -width 97 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -y 400 -anchor nw -bordermode ignore 
    place $site_3_0.tBu70 \
        -in $site_3_0 -x 420 -y 80 -width 97 -height 57 -anchor nw \
        -bordermode inside 
    place $site_3_0.che71 \
        -in $site_3_0 -x 350 -y 100 -anchor nw -bordermode ignore 
    menu $top.m69 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 20 -y 20 -width 565 -relwidth 0 -height 421 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

  set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

